version: "3.8"

services:
  database:
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  

volumes:
  pg_data: